# Environment

In [1]:
import os
os.chdir("..")

In [2]:
import pandas as pd

In [ ]:
amive_controle = pd.read_csv(f"../shared/Datasets/amive/amive_controle.csv")
amive_counts = pd.read_csv(f"../shared/Datasets/amive/amive_counts.csv")
amive_sentences = pd.read_csv(f"../shared/Datasets/amive/amive_sentences.csv")
amive_tokens = pd.read_csv(f"../shared/Datasets/amive/amive_tokens.csv")

# EDA

## Amive Controle

In [5]:
amive_controle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3972 entries, 0 to 3971
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DOCNO    3972 non-null   object
 1   TEXT     3972 non-null   object
 2   SYMPTOM  3972 non-null   object
dtypes: object(3)
memory usage: 93.2+ KB

In [6]:
amive_controle.head()

    DOCNO                                               TEXT SYMPTOM
0   100_1                  Segredos , por favor , me ajude !       _
1  100_10  Mas , quando estou sozinho comigo mesmo , perc...       _
2  100_13  As vezes quero dar um grito bem forte , pular ...       _
3  100_14                           Mas , não sei como . . .       _
4  100_16      Alguém pode me indicar algum grupo de apoio ?       _

## Amive Sentences

In [7]:
amive_sentences.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3367 entries, 0 to 3366
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DOCNO    3367 non-null   object
 1   TEXT     3367 non-null   object
 2   SYMPTOM  3367 non-null   object
dtypes: object(3)
memory usage: 79.0+ KB

In [8]:
amive_sentences.head()

,DOCNO,TEXT,SYMPTOM
0,100_10,"Mas , quando estou sozinho comigo mesmo , perc...",Sentimento de vazio
1,100_10,"Mas , quando estou sozinho comigo mesmo , perc...",Desamparo/Prejuízo social/Solidão
2,100_11,Me sinto cansado .,Cansaço/Desânimo/Desencorajamento/Fadiga/Perda...
3,100_12,Sinto que minha vida está sendo desperdiçada .,Cansaço/Desânimo/Desencorajamento/Fadiga/Perda...
4,100_12,Sinto que minha vida está sendo desperdiçada .,Desvalia/Baixa autoestima

In [9]:
amive_sentences["SYMPTOM"].unique().tolist()

['Sentimento de vazio',
 'Desamparo/Prejuízo social/Solidão',
 'Cansaço/Desânimo/Desencorajamento/Fadiga/Perda de energia/Lentificação',
 'Desvalia/Baixa autoestima',
 'Desesperança',
 'Tristeza/Humor depressivo',
 'Preocupação/Medo/Ansiedade',
 'Dificuldade para decidir',
 'Suicídio/Auto-extermínio',
 'Alteração na eficiência/funcionalidade',
 'Fator protetivo, cuidado em saúde e bem-estar',
 'Postagem com possível perfil depressivo',
 'Fator de risco',
 'Perda/diminuição do/da prazer/libido',
 'Morte/Suicídio de outro',
 'Irritação/Agressividade',
 'Alteração de peso/apetite',
 'Sintoma físico',
 'Sentimento de culpa',
 'Agitação/Inquietação',
 'Déficit de atenção/memória',
 'Alteração de sono']

In [10]:
amive_sentences[amive_sentences["SYMPTOM"] == "Fator de risco"].iloc[0]["TEXT"]

'Estou desempregado , iniciei acompanhamento com terapeuta ocupacional lá no < Instituiçao12 > , mas , sinto falta de um espeço onde eu puder desabafar , ter alguém pra me abraçar sem me senti constrangido por ser depressivo .'

## Amive Counts

In [11]:
amive_counts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SYMPTOM  22 non-null     object
 1   COUNT    22 non-null     int64
dtypes: int64(1), object(1)
memory usage: 484.0+ bytes

In [12]:
amive_counts

                                              SYMPTOM  COUNT
0                           Tristeza/Humor depressivo    473
1                                      Fator de risco    447
2                   Desamparo/Prejuízo social/Solidão    380
3             Postagem com possível perfil depressivo    337
4                            Suicídio/Auto-extermínio    278
5       Fator protetivo, cuidado em saúde e bem-estar    256
6                           Desvalia/Baixa autoestima    235
7                          Preocupação/Medo/Ansiedade    211
8                                        Desesperança    164
9              Alteração na eficiência/funcionalidade    155
10  Cansaço/Desânimo/Desencorajamento/Fadiga/Perda...    153
11                            Irritação/Agressividade    150
12                                Sentimento de culpa     73
13                            Morte/Suicídio de outro     67
14               Perda/diminuição do/da prazer/libido     43
15                                Sentimento de vazio     41
16                           Dificuldade para decidir     35
17                                     Sintoma físico     33
18                                  Alteração de sono     31
19                          Alteração de peso/apetite     17
20                         Déficit de atenção/memória     16
21                               Agitação/Inquietação     15

## Amive Tokens

In [13]:
amive_tokens.info()

<class 'pandas.DataFrame'>
RangeIndex: 3610 entries, 0 to 3609
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DOCNO    3610 non-null   str
 1   TEXT     3610 non-null   str
 2   TOKENS   3610 non-null   str
 3   SYMPTOM  3610 non-null   str
dtypes: str(4)
memory usage: 112.9 KB

In [14]:
amive_tokens.head()

,DOCNO,TEXT,TOKENS,SYMPTOM
0,100_10,"Mas , quando estou sozinho comigo mesmo , perc...","['percebo', 'a', 'imensidão', 'do', 'vazio', '...",Sentimento de vazio
1,100_10,"Mas , quando estou sozinho comigo mesmo , perc...","['quando', 'estou', 'sozinho', 'comigo', 'mesm...",Desamparo/Prejuízo social/Solidão
2,100_11,Me sinto cansado .,"['Me', 'sinto', 'cansado', '.']",Cansaço/Desânimo/Desencorajamento/Fadiga/Perda...
3,100_12,Sinto que minha vida está sendo desperdiçada .,"['Sinto', 'que', 'minha', 'vida', 'está', 'sen...",Cansaço/Desânimo/Desencorajamento/Fadiga/Perda...
4,100_12,Sinto que minha vida está sendo desperdiçada .,"['Sinto', 'que', 'minha', 'vida', 'está', 'sen...",Desvalia/Baixa autoestima