# Environment

In [1]:
import os
os.chdir("..")

In [2]:
import pandas as pd
from src.pipeline.bert import BertMultilabelConfig, PipelineBertMultilabel

from src.utils.map import SYMPTOM_MAP

In [3]:
MODEL_PATH = "./models/BERTimbau_depressive_symptoms"

## Data Load

In [4]:
df = pd.read_csv("./data/processed/amive.csv")

# Model

## Config

In [5]:
config = BertMultilabelConfig(
    model_path=MODEL_PATH,
    label_columns=list(SYMPTOM_MAP.values()),
    train_args={
        "num_train_epochs": 10,
        "per_device_train_batch_size": 16,
        "learning_rate": 2e-5,
        "warmup_ratio": 0.1,
        "weight_decay": 0.01,
        "eval_strategy": "epoch",
        "save_strategy": "epoch",
        "load_best_model_at_end": True,
        "metric_for_best_model": "eval_macro_avg_f1",
        "logging_strategy": "epoch",
        "report_to": "none",
    }
)

## Pipeline

In [6]:
pipeline = PipelineBertMultilabel(config)

### Data Split 

| Set | % |
| :--- | :---: |
| **Train** | 65 |
| **Val** | 20 |
| **Test** | 15 |

Divisão estratificada, que preserva a distribuição de cada label e suas combinações entre os splits

In [7]:
train_df, val_df, test_df = pipeline.split(df)

In [8]:
trainer = pipeline.train(train_df, val_df, text_column="TEXT")

Some weights of BertForMultiTaskClassification were not initialized from the model checkpoint at neuralmind/bert-large-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

### Results

In [9]:
results = pipeline.evaluate(trainer, test_df, text_column="TEXT")

In [10]:
display(results)

              precision    recall  f1-score  support
1              0.716049  0.865672  0.783784     67.0
2              0.851064  0.800000  0.824742     50.0
3              0.833333  0.769231  0.800000     39.0
4              0.807692  0.656250  0.724138     32.0
5              0.862069  0.833333  0.847458     30.0
6              0.600000  0.375000  0.461538     24.0
7              0.636364  0.318182  0.424242     22.0
8              1.000000  0.428571  0.600000     21.0
9              0.714286  0.714286  0.714286     21.0
micro avg      0.778182  0.699346  0.736661    306.0
macro avg      0.780095  0.640058  0.686688    306.0
weighted avg   0.781493  0.699346  0.724043    306.0
samples avg    0.733474  0.736990  0.718344    306.0

### Save Model

In [ ]:
pipeline.save(trainer)